### PR TITLE
Added Favicon and fixed site code

### PR DESCRIPTION
**Pull request by Hexsphere**
This is what I thought needed fixing on your site.

### CODE REVIEW

**Comment by EncryptrInb4** [comment]
How to merge?

**Comment by Hexsphere** [comment]
Use this https://help.github.com/articles/merging-a-pull-request/

**Comment by EncryptrInb4** [comment]
btw, I can't find Merge Button

**Comment by Hexsphere** [comment]
I think it is because there are conflicts with the HTML file.

**Comment by EncryptrInb4** [comment]
Ok, I'll take a look

**Comment by Hexsphere** [comment]
I think your gonna have to override all the issues in your Github desktop app.
https://help.github.com/desktop/guides/contributing/syncing-your-branch/

**Comment by EncryptrInb4** [comment]
Hmmm.. I don't see anything wrong :(

**Comment by Hexsphere** [comment]
Really? Weird

**Comment by Hexsphere** [comment]
Could you give me write access to this repo?

**Comment by EncryptrInb4** [comment]
aaand Sent.

**Comment by Hexsphere** [comment]
I'll merge my fork after I finish up my school. Thanks for letting me work with you on this! :D

**Comment by EncryptrInb4** [comment]
No, thank you for helping :)

**Comment by Hexsphere** [comment]
Your completely welcome!

**Comment by EncryptrInb4** [comment]
Back

**Comment by Hexsphere** [comment]
All done! All issues and conflicts cleared up! :D

**Pull request merged**
